const assert=require('assert/strict'),fs=require('fs');const {chromium}=require('playwright');const path=require('path');const root=path.resolve(__dirname,'..');
fs.mkdirSync(root+'/tmp',{recursive:true});
const server=require('child_process').spawn('python',['-m','http.server','8765','--bind','127.0.0.1'],{cwd:root});
(async()=>{await new Promise(r=>setTimeout(r,800));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.route('**/*.supabase.co/**',r=>r.abort());await page.goto('http://127.0.0.1:8765');
await page.locator('[data-ui-click="addApartment()"]').first().click();await page.locator('[data-ui-click="addVent(0)"]').click();if(!await page.locator('.room-group').evaluate(e=>e.open))await page.locator('.room-group>summary').click();if(!await page.locator('.vent-card').evaluate(e=>e.open))await page.locator('.vent-card>summary').click();await page.locator('.field-type select').selectOption('supply');await page.locator('.field-small input').first().fill('2');await page.locator('[data-adjusted-result]').fill('10');assert.equal(await page.locator('#summary-supply-0').textContent(),'20 l/s');await page.locator('.field-type select').selectOption('exhaust');assert.equal(await page.locator('#summary-exhaust-0').textContent(),'20 l/s');assert(await page.locator('.vent-card').evaluate(e=>e.open));
await page.locator('#default-exhaust-valve').fill('KSO-125');await page.locator('#default-supply-valve').fill('KTS-160');await page.locator('.field-type select').selectOption('supply');assert.equal(await page.locator('.field-valve input').inputValue(),'KTS-160');await page.locator('.field-type select').selectOption('exhaust');assert.equal(await page.locator('.field-valve input').inputValue(),'KSO-125');assert(await page.locator('.vent-card').evaluate(e=>e.open));await page.locator('.field-valve input').fill('Custom');await page.locator('.field-type select').selectOption('supply');assert.equal(await page.locator('.field-valve input').inputValue(),'Custom');await page.reload();assert.equal(await page.locator('#default-supply-valve').inputValue(),'KTS-160');assert.equal(await page.locator('#default-exhaust-valve').inputValue(),'KSO-125');
const photos=[];for(const [name,mime,ext]of [['png','image/png','png'],['gray','image/jpeg','jpeg'],['cmyk','image/jpeg','jpeg']]){const data='data:'+mime+';base64,'+fs.readFileSync(__dirname+'/browser-fixtures/'+name+'.'+ext).toString('base64');const result=await page.evaluate(async(data)=>{const a=await pdfJpegAsset(dataUrlBlob(data));return{width:a.width,height:a.height,magic:Array.from(a.bytes.slice(0,2))}},data);assert.deepEqual(result,{width:120,height:80,magic:[255,216]});photos.push({id:name,localKey:name,data,width:120,height:80});}
assert.equal(await page.evaluate(async()=>{try{await pdfJpegAsset(new Blob(['broken'],{type:'image/png'}));return false}catch(e){return true}}),true);
const project={format:'iv-mittaus-project',version:1,project:{projectId:'native-browser-test',kohde:'Selaintesti',paiva:'2026-10-05',workTypes:['measurement'],apartments:[{name:'A1',vents:Array.from({length:42},(_,i)=>({space:i%2?'Pyykkihuolto ja henkilökunnan pukuhuone':'Toimisto/tauko',type:'exhaust',kpl:'2',adjusted:'10'}))}],workEntries:[{id:'entry',date:'2026-10-05',title:'Kuvat',text:'PNG harmaasävy CMYK',photos}]}};
await page.locator('#project-import-file').setInputFiles({name:'test.ivprojekti.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await page.waitForFunction(()=>data.kohde==='Selaintesti');await page.reload();await page.waitForFunction(()=>data.kohde==='Selaintesti');assert.equal(await page.evaluate(()=>data.workEntries[0].photos.length),3);
await page.locator('[data-ui-click="generatePdf()"]').click();await page.locator('#pdf-modal.open').waitFor();const downloadPromise=page.waitForEvent('download');await page.locator('#pdf-download').click();await(await downloadPromise).saveAs(root+'/tmp/native-test.pdf');assert.deepEqual(errors,[]);console.log('Native Chromium PASS: mobile UI, 2×10=20, type change preserves open card, PNG/grayscale/CMYK decode and JPEG conversion, invalid image rejection, import/reload/photo persistence, real PDF download, zero CSP or JS errors.');await browser.close();server.kill()})().catch(e=>{console.error(e);server.kill();process.exit(1)});
